language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - sudo pip install codecov
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/vet

script:
  - make

after_success:
  - codecov
