language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/vet

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
